function addLoading(string = false) {
    var style = "<style id='loadinganimationO'>";
    style += ".sk-circle {";
    style += "margin: 50vh auto;";
    style += "width: 40px;";
    style += "height: 40px;";
    style += "position: relative;";
    style += "}";
    style += ".sk-circle .sk-child {";
    style += "width: 100%;";
    style += "height: 100%;";
    style += "position: absolute;";
    style += "left: 0;";
    style += "top: 0;";
    style += "}";
    style += ".sk-circle .sk-child:before {";
    style += "content: '';";
    style += "display: block;";
    style += "margin: 0 auto;";
    style += "width: 15%;";
    style += "height: 15%;";
    style += "background-color: #2ba3ff;";
    style += "border-radius: 100%;";
    style += "-webkit-animation: sk-circleBounceDelay 1.2s infinite ease-in-out both;";
    style += "animation: sk-circleBounceDelay 1.2s infinite ease-in-out both;";
    style += "}";
    style += ".sk-circle .sk-circle2 {";
    style += "-webkit-transform: rotate(30deg);";
    style += "-ms-transform: rotate(30deg);";
    style += "transform: rotate(30deg); }";
    style += ".sk-circle .sk-circle3 {";
    style += "-webkit-transform: rotate(60deg);";
    style += "-ms-transform: rotate(60deg);";
    style += "transform: rotate(60deg); }";
    style += ".sk-circle .sk-circle4 {";
    style += "-webkit-transform: rotate(90deg);";
    style += "-ms-transform: rotate(90deg);";
    style += "transform: rotate(90deg); }";
    style += ".sk-circle .sk-circle5 {";
    style += "-webkit-transform: rotate(120deg);";
    style += "-ms-transform: rotate(120deg);";
    style += "transform: rotate(120deg); }";
    style += ".sk-circle .sk-circle6 {";
    style += "-webkit-transform: rotate(150deg);";
    style += "-ms-transform: rotate(150deg);";
    style += "transform: rotate(150deg); }";
    style += ".sk-circle .sk-circle7 {";
    style += "-webkit-transform: rotate(180deg);";
    style += "-ms-transform: rotate(180deg);";
    style += "transform: rotate(180deg); }";
    style += ".sk-circle .sk-circle8 {";
    style += "-webkit-transform: rotate(210deg);";
    style += "-ms-transform: rotate(210deg);";
    style += "transform: rotate(210deg); }";
    style += ".sk-circle .sk-circle9 {";
    style += "-webkit-transform: rotate(240deg);";
    style += "-ms-transform: rotate(240deg);";
    style += "transform: rotate(240deg); }";
    style += ".sk-circle .sk-circle10 {";
    style += "-webkit-transform: rotate(270deg);";
    style += "-ms-transform: rotate(270deg);";
    style += "transform: rotate(270deg); }";
    style += ".sk-circle .sk-circle11 {";
    style += "-webkit-transform: rotate(300deg);";
    style += "-ms-transform: rotate(300deg);";
    style += "transform: rotate(300deg); }";
    style += ".sk-circle .sk-circle12 {";
    style += "-webkit-transform: rotate(330deg);";
    style += "-ms-transform: rotate(330deg);";
    style += "transform: rotate(330deg); }";
    style += ".sk-circle .sk-circle2:before {";
    style += "-webkit-animation-delay: -1.1s;";
    style += "animation-delay: -1.1s; }";
    style += ".sk-circle .sk-circle3:before {";
    style += "-webkit-animation-delay: -1s;";
    style += "animation-delay: -1s; }";
    style += ".sk-circle .sk-circle4:before {";
    style += "-webkit-animation-delay: -0.9s;";
    style += "animation-delay: -0.9s; }";
    style += ".sk-circle .sk-circle5:before {";
    style += "-webkit-animation-delay: -0.8s;";
    style += "animation-delay: -0.8s; }";
    style += ".sk-circle .sk-circle6:before {";
    style += "-webkit-animation-delay: -0.7s;";
    style += "animation-delay: -0.7s; }";
    style += ".sk-circle .sk-circle7:before {";
    style += "-webkit-animation-delay: -0.6s;";
    style += "animation-delay: -0.6s; }";
    style += ".sk-circle .sk-circle8:before {";
    style += "-webkit-animation-delay: -0.5s;";
    style += "animation-delay: -0.5s; }";
    style += ".sk-circle .sk-circle9:before {";
    style += "-webkit-animation-delay: -0.4s;";
    style += "animation-delay: -0.4s; }";
    style += ".sk-circle .sk-circle10:before {";
    style += "-webkit-animation-delay: -0.3s;";
    style += "animation-delay: -0.3s; }";
    style += ".sk-circle .sk-circle11:before {";
    style += "-webkit-animation-delay: -0.2s;";
    style += "animation-delay: -0.2s; }";
    style += ".sk-circle .sk-circle12:before {";
    style += "-webkit-animation-delay: -0.1s;";
    style += "animation-delay: -0.1s; }";
    style += "@-webkit-keyframes sk-circleBounceDelay {";
    style += "0%, 80%, 100% {";
    style += "    -webkit-transform: scale(0);";
    style += "    transform: scale(0);";
    style += "} 40% {";
    style += "      -webkit-transform: scale(1);";
    style += "      transform: scale(1);";
    style += "  }";
    style += "}";
    style += "@keyframes sk-circleBounceDelay {";
    style += "0%, 80%, 100% {";
    style += "    -webkit-transform: scale(0);";
    style += "    transform: scale(0);";
    style += "} 40% {";
    style += "      -webkit-transform: scale(1);";
    style += "      transform: scale(1);";
    style += "  }";
    style += "}";
    style += "</style>";
    if($("loadinganimationO").size()===0){
        $("head").append(style);
    }
    var a;
    if(string===false){
        a = "Mohon Tunggu";
    }else{
        a = string;
    }
    var content = "<div id='modal-loadingO' style='position:fixed;width: 100%;height: 100%;background: rgba(0,0,0,0.78);z-index: 999999'>";
    content += "<div class='sk-circle'>";
    content += "<div class='sk-circle1 sk-child'></div>";
    content += "<div class='sk-circle2 sk-child'></div>";
    content += "<div class='sk-circle3 sk-child'></div>";
    content += "<div class='sk-circle4 sk-child'></div>";
    content += "<div class='sk-circle5 sk-child'></div>";
    content += "<div class='sk-circle6 sk-child'></div>";
    content += "<div class='sk-circle7 sk-child'></div>";
    content += "<div class='sk-circle8 sk-child'></div>";
    content += "<div class='sk-circle9 sk-child'></div>";
    content += "<div class='sk-circle10 sk-child'></div>";
    content += "<div class='sk-circle11 sk-child'></div>";
    content += "<div class='sk-circle12 sk-child'></div>";
    content += "</div>";
    content += "<label style='color: white;position: absolute;top: 50%;'>"+a+"</label>";
    content += "</div>";
    $("body").prepend(content);
    a = $("#modal-loadingO").find("label").eq(0);
    a.css({"left":"calc(50% - "+(a.width()/2)+"px)"})


}

function removeLoading() {
    $("#modal-loadingO").remove();
}